<?php


namespace frontend\widgets\gallery;

use backend\modules\gallery\models\GalleryItem;
use yii\base\Widget;

class Gallery extends Widget
{
    public $options = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $items = GalleryItem::find()->where(['status' => 1])->andWhere(['deleted' => 0])->all();
         return $this->render('gallery_items', [
             'items' => $items,
         ]);

        //parent::run(); // TODO: Change the autogenerated stub
    }
}