<?php
/**
 * Created by PhpStorm.
 * User: miller
 * Date: 16/01/24
 * Time: 22:07
 */

namespace frontend\widgets\navigationMenu;


use yii\base\Widget;
use yii\bootstrap4\NavBar;
use yii\bootstrap4\Nav;

class NavigationMenu extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $this->render('navbar', [

        ]);
    }
}